display: Fix module display_intf_headers dependency
error: hardware/qcom-caf/sm8350/display/Android.bp:81:1: "display_headers" depends on undefined module "display_intf_headers".
Module "display_headers" is defined in namespace "." which can read these 9 namespaces: ["." "." "vendor/oplus/camera" "hardware/oplus" "vendor/oneplus/oneplus9" "device/oneplus/oneplus9" "vendor/qcom/opensource/usb/etc" "hardware/oplus/overlay/generic" "hardware/oplus/overlay/qssi"]
Module "display_intf_headers" can be found in these namespaces: ["hardware/qcom-caf/msm8996" "hardware/qcom-caf/msm8998" "hardware/qcom/display/msm8909" "vendor/qcom/opensource/commonsys-intf/display"]
Or did you mean ["libdisplayconfig.qti"]?

Change-Id: f75957e872a5a052a12bf34c1f0fb59b31801052
Signed-off-by: TogoFire <togofire@mailfence.com>
Signed-off-by: Omar Mohamed <omarcoptan9@gmail.com>